### PR TITLE
feat: add default time zone setting

### PR DESCRIPTION
**Pull request by a65162**

### CODE REVIEW

**Review by potato4d — COMMENTED** [review]
Great work!

Would you like write API description to README?

**Comment by a65162** [comment]
Sure. I forgot it.

**Comment by a65162** [comment]
Done.

**Review by potato4d — APPROVED** [review]
Thank you!

LGTM

**Comment by potato4d** [comment]
@a65162 
I have just released v1.3.0 and this is included in that version!

**Comment by a65162** [comment]
@potato4d 
Thanks. 
Now, It works on my project.

**Comment by potato4d** [comment]
@all-contributors add @a65162 code

**Pull request merged**
